services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: book_app_development
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0"
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://postgres:password@db:5432/book_app_development
      GOOGLE_BOOKS_API_KEY: AIzaSyC1XBticNsjDga9zYCM7wt2ny6ZkLrtznk

volumes:
  postgres_data:
